steps:

# Step 1: Download the Model
- name: 'gcr.io/cloud-builders/gcloud'
  id: 'Download Model'
  entrypoint: 'bash'
  args:
    - '-c'
    - |
      mkdir -p models
      gcloud storage cp gs://kadis-bucket/models/best_model.pt models/model.pth

# Step 2: Create directory and Download Preprocessing Artifacts
- name: 'gcr.io/cloud-builders/gcloud'
  id: 'Download Preprocessing Artifacts'
  entrypoint: 'bash'
  args:
    - '-c'
    - |
      mkdir -p data/processed
      gcloud storage cp gs://kadis-bucket/data/processed/scaler.joblib data/processed/
      gcloud storage cp gs://kadis-bucket/data/processed/feature_columns.json data/processed/
      gcloud storage cp gs://kadis-bucket/data/processed/label_encoder.joblib data/processed/

# Step 3: Build the container image
- name: 'gcr.io/cloud-builders/docker'
  id: 'Build container image'
  args: [
    'build',
    '-t', 'europe-west1-docker.pkg.dev/dtumlops-484207/eval/api:latest',
    '-f', 'dockerfiles/api.dockerfile',
    '.'
  ]

# Step 4: Push to Artifact Registry
- name: 'gcr.io/cloud-builders/docker'
  id: 'Push container image'
  args: [
    'push',
    'europe-west1-docker.pkg.dev/dtumlops-484207/eval/api:latest'
  ]

# Step 5: Deploy to Cloud Run
- name: 'gcr.io/cloud-builders/gcloud'
  id: 'Deploy to Cloud Run'
  args: [
    'run',
    'deploy',
    'api',
    '--image', 'europe-west1-docker.pkg.dev/dtumlops-484207/eval/api:latest',
    '--region', 'europe-west1',
    '--platform', 'managed',
    '--port', '8000',             # FastAPI default port
    '--memory', '4Gi',            # Matches docker memory limits
    '--cpu', '1',
    '--timeout', '300s',
    '--concurrency', '80',
    '--max-instances', '3',
    '--cpu-boost',
    '--service-account', '934984265576-compute@developer.gserviceaccount.com',
    '--allow-unauthenticated',
  ]

options:
  logging: CLOUD_LOGGING_ONLY
