solver:
  name: hc_predictor
  model_name: HC
  custom_objective: lagrange
  N_SELECT_FEATURES: 5
  n_runs: 5
  recalculate_dag: true
  feature_selector: SequentialFeatureSelector
  n_outer: 10
  n_inner: 100
  hidden_dim: 32
  depth: 2
  constrained: true
  rho0: 0
  lambda0: 1.0
  rho_mult: 1.0
  learning_rate: 0.25
  lambda_update_rate: 1.0
  weight_decay: 0.25
  loss_type: l2
  reg_type: l2
  a_reg_type: l1
  lambda1: 0.1
  lambda2: 0.1
  nonzero_threshold: 0.001
  constraints_mode: weights
  callback_mode: all_cycles
  robust: false
  tabu_edges: false
  weights_bound: 1.0
  time_limit: 1800
  target_mip_gap: 0.0001
  data_path: ./data/
  knowledge_graph_filename: knowledge_graph_intersection.graphml
  debug: false
problem:
  name: industry_eu
  data_path: data/industry_eu/processed/industry_eu_oecd_ExcludingConstruction_allcountry_monthly_89x25.csv
  frequency: M
  impute: none
  dropna_selected: true
  target: ESP
  features:
  - AUT
  - BEL
  - CHE
  - CZE
  - DEU
  - DNK
  - EST
  - FIN
  - FRA
  - GRC
  - HUN
  - IRL
  - ISL
  - ITA
  - LTU
  - LUX
  - LVA
  - NLD
  - NOR
  - POL
  - PRT
  - SVK
  - SVN
  - SWE
experiment: recommender_industry
