# prep:
#   use_pca: true
#   pca_print: false
#   pca_blocks:
#     - name: ms_serum
#       n_dims: 10
#     - name: ms_urine
#       n_dims: 10
#     - name: nmr_urine
#       n_dims: 15
#   use_lipidomics: true
#   use_single_microbiome_alpha: false
#   continental_sites: ["AUTH", "BILBAO", "UVEG"]
#   non_food_prefixes:
#     - microbiome
#     - scafs
#     - ms_serum.pca
#     - ms_urine.pca
#     - nmr_urine.pca


defaults:
  - target: default
  - data: default
  - experiment: GP
  - _self_

seed: 2227070966

paths:
  read_data_dir: /Users/xiaoyuhe/Recommender_System/data/raw
  save_data_dir: /Users/xiaoyuhe/Recommender_System/data/process

    
prep:
  use_pca: true
  pca_print: false
  pca_blocks:
    - name: ms_serum
      n_dims: 10
    - name: ms_urine
      n_dims: 10
    - name: nmr_urine
      n_dims: 15
  use_lipidomics: true
  use_single_microbiome_alpha: false
  continental_sites: ["AUTH", "BILBAO", "UVEG"]
  non_food_prefixes:
    - microbiome
    - scafs
    - ms_serum.pca
    - ms_urine.pca
    - nmr_urine.pca
