#!/usr/bin/env bash
# Phase 1: audit whether graph-derived constraints are valid for a predictor
# before applying them to observational data.  The result table is paired by
# graph/noise realization across every arm.

GRAPH_SEEDS="${GRAPH_SEEDS:-${SEEDS:-42 43 44}}"
NOISE_SEEDS="${NOISE_SEEDS:-101}"
SEEDS="${GRAPH_SEEDS}"
source "$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)/_common.sh"

announce_stage "01" "synthetic constraint screen"

PROBLEMS="${PROBLEMS:-synthetic_er,synthetic_sf}"
EXPERIMENT_PREFIX="${EXPERIMENT_PREFIX:-PLAN01_SYNTHETIC}"
TIME_LIMIT="${TIME_LIMIT:-120}"
N_RUNS="${N_RUNS:-5}"
N_OUTER="${N_OUTER:-10}"
N_INNER="${N_INNER:-100}"
N_SAMPLES="${N_SAMPLES:-1000}"
N_NODES="${N_NODES:-10}"
EXPECTED_EDGES="${EXPECTED_EDGES:-15}"
INCLUDE_DEPENDENT="${INCLUDE_DEPENDENT:-0}"

read -r -a PHASE1_NOISE_SEEDS <<< "${NOISE_SEEDS//,/ }"
if [[ ${#PHASE1_NOISE_SEEDS[@]} -eq 0 ]]; then
  die "NOISE_SEEDS must contain at least one integer."
fi

export HC_CONSTRAINT_BACKEND="${HC_CONSTRAINT_BACKEND:-alm}"
export HC_WEIBULL_GAUSSIANIZE=0

COMMON=(
  "solver.time_limit=${TIME_LIMIT}"
  "solver.n_runs=${N_RUNS}"
  "solver.n_outer=${N_OUTER}"
  "solver.n_inner=${N_INNER}"
  "solver.feature_selector=none"
  "solver.dag_fit_scope=inner_train"
  "solver.constraint_audit_enabled=true"
  "solver.ci_target_related_only=true"
  "solver.ci_target_constraint_role=endpoint"
  "solver.ce_use_balanced_batches=false"
  "solver.ce_batch_size=128"
  "solver.use_stochastic_constrained_optimizer=false"
  "++problem.n_samples=${N_SAMPLES}"
  "++problem.n_nodes=${N_NODES}"
  "++problem.expected_edges=${EXPECTED_EDGES}"
  "++problem.sem_type=gauss"
)

# Unlike run_seeded(), this explicitly separates a graph/structural-coefficient
# seed from an innovation-noise seed.  The combined model seed is identical
# for all arms of one graph/noise realization, making method comparisons paired.
run_phase1_synthetic() {
  local label="$1"
  local solver="$2"
  shift 2

  local graph_seed noise_seed model_seed
  for graph_seed in "${PLAN_SEEDS[@]}"; do
    [[ "${graph_seed}" =~ ^[0-9]+$ ]] || die "Invalid GRAPH_SEEDS value ${graph_seed}."
    for noise_seed in "${PHASE1_NOISE_SEEDS[@]}"; do
      [[ "${noise_seed}" =~ ^[0-9]+$ ]] || die "Invalid NOISE_SEEDS value ${noise_seed}."
      model_seed="$((graph_seed * 100000 + noise_seed))"
      export HC_SPBM_RANDOM_SEED="${model_seed}"
      local -a seed_overrides=(
        "solver.random_state=${model_seed}"
        "solver.cv_random_state=$((model_seed + 10000))"
        "solver.validation_random_state=$((model_seed + 20000))"
        "++problem.seed=${graph_seed}"
        "++problem.graph_seed=${graph_seed}"
        "++problem.noise_seed=${noise_seed}"
      )
      if (( ${#PLAN_EXTRA_OVERRIDES[@]} > 0 )); then
        run_hydra "${EXPERIMENT_PREFIX}_${label}_graph${graph_seed}_noise${noise_seed}" \
          "${solver}" "${PROBLEMS}" "${seed_overrides[@]}" "$@" "${PLAN_EXTRA_OVERRIDES[@]}"
      else
        run_hydra "${EXPERIMENT_PREFIX}_${label}_graph${graph_seed}_noise${noise_seed}" \
          "${solver}" "${PROBLEMS}" "${seed_overrides[@]}" "$@"
      fi
    done
  done
}

# S0: predictive DNN only. HC-CE is used so the network and validation path
# match the CE arms while every graph-derived term is disabled.
run_phase1_synthetic "s0_no_constraint" "hc_predictor_ce" \
  "${COMMON[@]}" \
  "solver.constrained=false" \
  "solver.recalculate_dag=false" \
  "solver.use_w_constraints=false" \
  "solver.use_ci_penalty=false" \
  "solver.constraint_audit_oracle=none"

# S1: true synthetic W constraint. recalculate_dag=false selects the W_true
# generated by synthetic_utils rather than fitting a new graph from each fold.
run_phase1_synthetic "s1_true_w" "hc_predictor_ce" \
  "${COMMON[@]}" \
  "solver.constrained=true" \
  "solver.recalculate_dag=false" \
  "solver.use_w_constraints=true" \
  "solver.w_matrix_space=raw_sem" \
  "solver.use_ci_penalty=false" \
  "solver.constraint_audit_oracle=synthetic_linear_sem"

# S2: true-DAG d-separation independences only. Dependence constraints are not
# hard causal facts, so they are excluded from the default phase-1 screen.
run_phase1_synthetic "s2_true_independent" "hc_predictor_ce" \
  "${COMMON[@]}" \
  "solver.constrained=true" \
  "solver.recalculate_dag=false" \
  "solver.use_w_constraints=false" \
  "solver.w_matrix_space=raw_sem" \
  "solver.use_ci_penalty=true" \
  "solver.ci_penalty_kind=conditional_expectation" \
  "solver.ce_constraint_backend=alm_pbm" \
  "solver.ci_add_dsep_independence=true" \
  "solver.ci_add_collider_marginal_independence=false" \
  "solver.ci_add_collider_conditional_dependence=false" \
  "solver.ci_add_shielded_collider_dependence=false" \
  "solver.constraint_audit_oracle=synthetic_linear_sem"

# S3 is deliberately opt-in because a lower-bound dependence penalty remains
# exploratory even when evaluated with an absolute residual covariance. The
# default target X9 is terminal in this generator, so it cannot be a parent in
# x -> collider <- X9; this arm is expected to record zero target-endpoint
# dependent constraints. It is retained as an explicit negative control, not
# as evidence for the dependent-constraint claim.
if [[ "${INCLUDE_DEPENDENT}" == "1" ]]; then
  run_phase1_synthetic "s3_true_independent_dependent_exploratory" "hc_predictor_ce" \
    "${COMMON[@]}" \
    "solver.constrained=true" \
    "solver.recalculate_dag=false" \
    "solver.use_w_constraints=false" \
    "solver.w_matrix_space=raw_sem" \
    "solver.use_ci_penalty=true" \
    "solver.ci_penalty_kind=conditional_expectation" \
    "solver.ce_constraint_backend=alm_pbm" \
    "solver.ci_add_dsep_independence=true" \
    "solver.ci_add_collider_marginal_independence=false" \
    "solver.ci_add_collider_conditional_dependence=true" \
    "solver.ci_add_shielded_collider_dependence=false" \
    "solver.ci_dependent_statistic=absolute" \
    "solver.constraint_audit_oracle=synthetic_linear_sem"
fi

# S4 separates graph-estimation error from the true-W arms above.
run_phase1_synthetic "s4_estimated_independent" "hc_predictor_ce" \
  "${COMMON[@]}" \
  "solver.constrained=true" \
  "solver.recalculate_dag=true" \
  "solver.use_w_constraints=false" \
  "solver.use_ci_penalty=true" \
  "solver.ci_penalty_kind=conditional_expectation" \
  "solver.ce_constraint_backend=alm_pbm" \
  "solver.ci_add_dsep_independence=true" \
  "solver.ci_add_collider_marginal_independence=false" \
  "solver.ci_add_collider_conditional_dependence=false" \
  "solver.ci_add_shielded_collider_dependence=false" \
  "solver.constraint_audit_oracle=synthetic_linear_sem"

# Each PBS job writes a self-contained *partial* summary under results/, which
# is copied back by the PBS launcher.  To aggregate several graph-seed jobs,
# run summarize_phase1.py later with one --scan-root per copied job directory.
# Setting SKIP_PHASE1_SUMMARY=1 is useful only for a deliberate partial rerun.
if [[ "${SKIP_PHASE1_SUMMARY:-0}" != "1" && "${DRY_RUN}" != "1" ]]; then
  "${PYTHON_BIN}" scripts/causal_predictor_plan/summarize_phase1.py \
    --scan-root "${PHASE1_SCAN_ROOT:-multirun}" \
    --output-dir "${PHASE1_SUMMARY_DIR:-results/phase1}" \
    --experiment-prefix "${EXPERIMENT_PREFIX}"
fi
