hydra:
  launcher:
    n_jobs: 1
    prefer: processes
#    prefer: processes # use processes instead of threads
#    backend: multiprocessing # use multiprocessing backend instead of loky
  sweeper:
    # max_batch_size: 500 # - only for cluster
    params:

experiment: recommender_industry
defaults:
  - solver: hc_predictor
  - problem: OECD_9country_monthly/industry_eu_aut
  - override hydra/launcher: joblib
  - _self_
