hydra:
  sweeper:
    max_batch_size: 500 # There is a quota on RCI cluster that limits number of scheduled jobs to 500.
    params:

experiment: CODIET_RECOMMENDER
defaults:
  - solver: mark
  - problem: codiet
  - override hydra/launcher: configured_submitit_slurm
  - _self_

