name: hc_predictor
model_name: HC
custom_objective: lagrange
N_SELECT_FEATURES: 5
n_runs: 5
recalculate_dag: true
feature_selector: SequentialFeatureSelector
n_outer: 10
n_inner: 400
hidden_dim: 16
depth: 3
device: cpu
constrained: false
rho0: 1.0
lambda0: 1.0
rho_mult: 1.0
learning_rate: 0.05
lambda_update_rate: 0.25
weight_decay: 0.25
lr_decay: 0.7
verbose: true
loss_type: l2
reg_type: l2
a_reg_type: l1
lambda1: 0.1
lambda2: 0.1
nonzero_threshold: 0.001
constraints_mode: weights
callback_mode: all_cycles
robust: false
tabu_edges: false
weights_bound: 1.0
time_limit: 1800
target_mip_gap: 0.0001
data_path: ./data/
knowledge_graph_filename: knowledge_graph_intersection.graphml
debug: false
