name: mark
model_name: XGB
custom_objective: reg:squarederror #mse_builtin #mse_custom
N_SELECT_FEATURES: 5
n_runs: 5
recalculate_dag: true

n_estimators: 10
max_depth: 3
learning_rate: 0.1
random_state: 42

feature_selector: SequentialFeatureSelector


# debugging
debug: false