#!/usr/bin/env bash
# dashboard-step4-sync: v1
# Generated by 自动发文章 Dashboard. Do not put experiment parameters here.
set -euo pipefail

PROJECT_ID=project-469fc1ce65c2
PROJECT_ROOT=/Users/xiaoyuhe/Recommender_Pavel
SCRIPTS_DIR=/Users/xiaoyuhe/Recommender_Pavel/scripts
RESULTS_DIR=/Users/xiaoyuhe/Recommender_Pavel/dagsolvers/results
MLFLOW_TRACKING_URI="${MLFLOW_TRACKING_URI:-/Users/xiaoyuhe/Recommender_Pavel/dagsolvers/mlruns}"
export PROJECT_ID PROJECT_ROOT SCRIPTS_DIR RESULTS_DIR MLFLOW_TRACKING_URI

# Prefer a project-owned summary command. The dashboard only dispatches this
# wrapper; it never guesses Hydra groups or rewrites existing launchers.
for summary_script in \
  "${SCRIPTS_DIR}/summary_multiruns.sh" \
  "${SCRIPTS_DIR}/summary_industry.sh"; do
  if [[ -f "${summary_script}" ]]; then
    exec sh "${summary_script}" "$@"
  fi
done

if [[ -f "${PROJECT_ROOT}/multirun_summary_mlflow.py" ]]; then
  if [[ "$#" -eq 0 ]]; then
    echo "[dashboard] codiet_recommender: 请通过项目 summary_*.sh 指定 MLflow group。" >&2
    exit 2
  fi
  exec "${PYTHON_BIN:-python3}" "${PROJECT_ROOT}/multirun_summary_mlflow.py" --source auto "$@"
fi

echo "[dashboard] codiet_recommender: 未发现项目级 Multirun/MLflow summary 命令；仅完成脚本目录同步。"
